# Generated by Django 2.0.2 on 2018-02-12 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timeclock', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useractivity',
            options={'verbose_name': 'Activity', 'verbose_name_plural': 'User Activities'},
        ),
    ]
